# 基础镜像
# FROM  openjdk:8-jre
FROM openjdk:8-jdk-slim
# author
MAINTAINER zhaoxi

# 指定容器内部挂载目录
VOLUME /home/freeapi
# 在容器中创建目录
RUN mkdir -p /home/freeapi
# 指定工作路径
WORKDIR /home/freeapi
# 复制jar文件到路径
COPY ./jar/freeapi-gateway.jar /home/freeapi/freeapi-gateway.jar
# 容器对外暴露的端口，好像没必要暴露
# EXPOSE 8080
# 启动网关服务
ENTRYPOINT ["java","-jar","freeapi-gateway.jar"]