# 公共配置文件
server:
  port: 9527
  servlet:
    context-path: /api
  # Druid 配置
spring:
  application:
    name: freeapi-core
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.145.128:3306/freeapi
      username: root
      password: 123456
      db-type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 47.96.37.10
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 这段配置仅供测试，实际应该根据登录用户获取对应的 ak、sk
freeapi:
  client:
    access-key: zhaoxi
    secret-key: abcdefgh
#配置阿里云短信服务
  sms:
    access-key: LTAI5tAohvtnaizrLRhTeFcA
    secret-key: vTStp41z6zd5p6t8RXXLc5tVqXcejO
dubbo:
  application:
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://192.168.145.128:8848
