# 基础镜像
FROM nginx
# author
MAINTAINER zhaoxi

# 指定容器内部挂载目录
VOLUME /home/zhaoxi/projects/freeapi-ui
# 在容器中创建目录
RUN mkdir -p /home/zhaoxi/projects/freeapi-ui
# 指定工作路径
WORKDIR /home/zhaoxi/projects/freeapi-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/zhaoxi/projects/freeapi-ui
