# 公共配置文件

server:
  port: 8080
spring:
  application:
    name: freeapi-gateway
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://192.168.145.128:7529"
              - "http://192.168.145.128:8123"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      default-filters:
        - AddResponseHeader=source, zhaoxi
      routes:
        - id: api_route
          uri: http://192.168.145.128:8123
          predicates:
            - Path=/api/**
#        - id: add_request_header_route
#          uri: http://192.168.145.128:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=zhaoxi, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: zhaoxi-fallback
#          uri: https://zhaoxi.icu
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace


dubbo:
  application:
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://192.168.145.128:8848

